### ISSUE TITLE
Support node pre 7.5

### ISSUE THREAD

**Issue by sw-yx** [nmaro/ooth#1]
hi! just trying to try out your basic ooth example. couldnt get it to start. here's what happened after npm install:

```
> node --harmony-async-await index.js

node: bad option: --harmony-async-await

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! ooth-example@0.1.0 start: `node --harmony-async-await index.js`
npm ERR! Exit status 9
npm ERR! 
npm ERR! Failed at the ooth-example@0.1.0 start script 'node --harmony-async-await index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ooth-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node --harmony-async-await index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ooth-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ooth-example
npm ERR! There is likely additional logging output above.
```

i am on node 6.9.4  and from googling this harmony-async-await problem it looks like node 7 is required. however it is not the active version of node. is this a required dependency?

**Comment by nmaro** [comment]
Hi there! Thanks for checking it out. You are right, I should document that for now ooth works only with node 7.5 to support async/await out of the box.

To support earlier node versions I either have to transpile it with babel, or use promises instead of async/await. Right now I'm focused on creating an accounts UI but I'll keep this open as a reminder and to track demand for this feature.

**Comment by sw-yx** [comment]
i agree its low priority given node 8 will be released soon. i was just checking to make sure i didnt make some silly mistake. i will likely revisit as soon as node 8 is out

Sw yx

Sent from
https://polymail.io/?utm_source=polymail&utm_medium=referral&utm_campaign=signature

On Tue, Mar 28, 2017 at 1:18 AM Nick Redmark

<
mailto:Nick Redmark <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

Hi there! Thanks for checking it out. You are right, I should document that for now ooth works only with node 7.5 to support async/await out of the box.

To support earlier node versions I either have to transpile it with babel, or use promises instead of async/await. Right now I'm focused on creating an accounts UI but I'll keep this open as a reminder and to track demand for this feature.

—

You are receiving this because you authored the thread.

Reply to this email directly,
https://github.com/nmaro/ooth/issues/1#issuecomment-289697505
, or

**Comment by nmaro** [comment]
Now all packages are compiled it could possibly even work - I don't really know, I don't feel like trying. I don't think people are interested in this, so wontfix for the time being.

**Comment by nmaro** [comment]
Feel free to reopen if this is really important to you.
