### ISSUE TITLE
getUniqueField is missing

### ISSUE THREAD

**Issue by adcooley** [nmaro/ooth#10]
Getting an error when I try to Reset Password after only registering in Facebook (in the example app you created). Went to the library and it looks like this isn't defined anywhere

Error is "getUniqueField is not defined"

https://github.com/nmaro/ooth/blob/a1cc2a04ad645662999ed8d4d950f2aba1008da2/packages/ooth-local/src/index.js#L258

**Comment by nmaro** [comment]
Thanks, yes, it should be defined in line 71 but it isn't. I'll fix asap.

**Comment by nmaro** [comment]
Should be fixed in ooth and ooth-local 0.12.3
