### ISSUE TITLE
Suggestion: Abstract db backend

### ISSUE THREAD

**Issue by AnsonT** [nmaro/ooth#11]
Would be great to abstract out the db backend, so non-MongoDB can be used. FeatherJS is a good example of abstracting DB operations.

**Comment by nmaro** [comment]
Done

**Comment by nmaro** [comment]
@AnsonT if you plan to create a non-mongo backend please let me know. Should be extremely easy based on the mongo example (52 lines of code): https://github.com/nmaro/ooth/blob/master/packages/ooth-mongo/src/index.js
