### ISSUE TITLE
API runnable with node 8.7?

### ISSUE THREAD

**Issue by jaqua** [nmaro/ooth#19]
I'm trying to get `graphql-api-with-auth` running. I'm using node 8.7. After running `npm run start` I can't access `http://localhost:3002/graphiql` or `http://localhost:3002/guest/register`. I do get the error `Cannot GET ...`

**Comment by nmaro** [comment]
Yes, sorry, the examples are out of date, it's a ticket, see https://github.com/nmaro/ooth/issues/7
The most up-to-date example is the staart project: https://staart.nmr.io/

I will keep this as a placeholder to test all the examples with node 8.

**Comment by nmaro** [comment]
Tests are updated and run with node 8
