### ISSUE TITLE
Exemple nextjs : Invariant Violation when refreshing the page

### ISSUE THREAD

**Issue by Aetherall** [nmaro/ooth#2]
Hi,
I am really interested on using your nextjs integration exemple with apollo, as a base for my personal projects.

I encountered 2 errors :

The first one is simply about renaming settings.dist.js to settings.js, so the import can occurs

Unfortunately I can not figure out what causes the second error :

> { Invariant Violation: Objects are not valid as a React child (found: 5923bbe80115a80a2d96abe0). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of 'LoginStatusComponent'.
>
>     at invariant (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/fbjs/lib/invariant.js:44:15)
>     at traverseAllChildrenImpl (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/traverseAllChildren.js:144:56)
>     at traverseAllChildrenImpl (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/traverseAllChildren.js:93:23)
>     at traverseAllChildren (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/traverseAllChildren.js:172:10)
>     at Object.instantiateChildren (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactChildReconciler.js:70:7)
>     at ReactDOMComponent._reconcilerInstantiateChildren (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactMultiChild.js:187:41)
>     at ReactDOMComponent.mountChildren (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactMultiChild.js:226:27)
>     at ReactDOMComponent._createContentMarkup (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactDOMComponent.js:653:32)
>     at ReactDOMComponent.mountComponent (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactDOMComponent.js:520:29)
>     at Object.mountComponent (/mnt/c/Users/Elies/Workspace/next/bug/node_modules/react-dom/lib/ReactReconciler.js:46:35) name: 'Invariant Violation', framesToPop: 1 }

To reproduce it:
- clone the repo
- navigate to ooth-next-with-api exemple
- yarn install
- npm run start
- open in browser
- click login
- refresh
 
Thanks for help !

Edit : 

I've finally figured this out,
```javascript
class LoginStatusComponent extends Component {
	render() {
		const { oothClient, user } = this.props
		if( user ) {
			return (
				<div>
					Your user id is {user._id.toString()}    // added .toString()
					<button onClick={() => {
						oothClient.logout()
					}}>Log out
					</button>
				</div>
			)
		} else {
			return <div>
				Click on the button to create a guest session.<br />
				<button onClick={() => {
					oothClient.authenticate('guest', 'register')
						.catch(err => {
							console.error(err)
						})
				}}>Log in
				</button>
			</div>
		}
	}
}

**Comment by nmaro** [comment]
Hey, thanks for trying it out! Your fix suggests that _id is a string on the client, and a Mongo ID object on the server - which is a bug. I'll fix it asap.

**Comment by nmaro** [comment]
Tests are now up-to-date.
