### ISSUE TITLE
Project Staart. 404!

### ISSUE THREAD

**Issue by vijayant123** [nmaro/ooth#3]
Hi,

I could find the Staart project anywhere on the Internet. Please share some info about it.

Regards,
Vijayant Saini

**Comment by nmaro** [comment]
True! The link was broken, thanks for pointing it out to me. Fixed it now.

The project is available here: https://github.com/nmaro/ooth
An introducing article is here: https://medium.com/@nmaro/staart-a-starter-library-for-node-js-projects-with-user-accounts-d1328b46a59

Thank you for checking this out :)
