### ISSUE TITLE
Proposal: Use some config package

### ISSUE THREAD

**Issue by katsanva** [nmaro/ooth#31]
@nmaro , I propose to use some config package like [node-config](https://github.com/lorenwest/node-config) instead of present `*.dist.js` things.
If confirmed I'll make a PR for this.

**Comment by nmaro** [comment]
Yes, I'd welcome this change - are you familiar with dotenv? (https://github.com/motdotla/dotenv/). Would have been my choice, but I don't know node-config, so don't know the difference.

**Comment by katsanva** [comment]
Yep, `dotenv` is pretty neat, when talking about environment variables. But IMO a tool like `node-config` is much better when talking about file-based, object-based configs, as has shown in [`ooth`](https://github.com/nmaro/ooth/blob/master/examples/standalone/ooth/settings.dist.js). 

And `node-config` supports env variables too. :) 

Also, there is a note about [storing default config files in repo](https://github.com/motdotla/dotenv/#should-i-commit-my-env-file) in `dotenv` - TL;DR it's strongly not recommended.
