### ISSUE TITLE
Make ooth messages customizable (and internationalizable)

### ISSUE THREAD

**Issue by nmaro** [nmaro/ooth#36]
Most Ooth and ooth plugin messages are currently hardcoded, move them i18n/en.json and make them configurable.

**Comment by ela34** [comment]
Also it would be nice to get an error code as well as the text message. This will ease implementing specific behaviors depending on the error.

**Comment by nmaro** [comment]
This is done. @ela34 I opened a new ticket for your request: https://github.com/nmaro/ooth/issues/61
