### ISSUE TITLE
Supporting user role?

### ISSUE THREAD

**Issue by caoer** [nmaro/ooth#38]
any thoughts on it?

**Comment by caoer** [comment]
https://github.com/jedireza/aqua/ did a pretty good job. but it's design is not as extensible as ooth.

**Comment by caoer** [comment]
I haven't try ooth yet, just think about it and there isn't an integrated good framework for user identity, like what ruby have, devise, and others.
recommend following two places to read.
auth0 seems did a very good job on authorization in a commercial sense. 

- https://github.com/jedireza/aqua/wiki/Users,-Roles-&-Groups
- https://auth0.com/rules/roles-creation
- https://github.com/plataformatec/devise  

In this topic, I would image that there is one special account, who is owner/agent. it can have the power to give/assign to others. 

or the plugin may just expose the API to let developer decided what to do with it.

**Comment by nmaro** [comment]
Hey @caoer I was inspired and created a pretty simple roles plugin, here's how to use it:

* server side: https://github.com/nmaro/ooth/wiki#managing-user-roles
* client side: https://github.com/nmaro/ooth/wiki#managing-user-roles-1

Let me know if that helps you.
