### ISSUE TITLE
TypeError: this.route.ws is not a function

### ISSUE THREAD

**Issue by gferreri** [nmaro/ooth#42]
When calling `ooth.start` I see the error

>>>TypeError: this.route.ws is not a function
    at Ooth.start (/Users/gsferrer/Projects/myProject/node_modules/ooth/lib/index.js:211:24)

Looking at the source, it appears that `expressws(app)` is called in `start()` after the router has been created in the Ooth constructor.

From the [express-ws](https://github.com/HenningM/express-ws#usage) README:

>>>Important: Make sure to set up the express-ws module like above before loading or defining your routers! Otherwise, express-ws won't get a chance to set up support for Express routers, and you might run into an error along the lines of router.ws is not a function.

**Comment by aaronmgdr** [comment]
ah so its not just me

**Comment by cheri3a** [comment]
same her

**Comment by nmaro** [comment]
Thanks for the report, I'll give it a look tomorrow.

**Comment by aaronmgdr** [comment]
thanks!

**Comment by nmaro** [comment]
Hello everyone, sorry for the delay. It would help me to know the difference between your setup and this example which works for me without error: https://github.com/nmaro/ooth/blob/master/examples/standalone/ooth/index.js

**Comment by gferreri** [comment]
So I no longer see this error, and I'm not 100% sure what I did to fix it :-/. I believe it had something to do with the order of calls to `express.use` in my app. The standalone example works fine for me as well.

**Comment by nmaro** [comment]
Assuming it's not a bug, otherwise leave a comment.
