### ISSUE TITLE
Bcrypt cost factor

### ISSUE THREAD

**Issue by pdiniz13** [nmaro/ooth#45]
It looks like you are currently using a salt cost of 10. https://github.com/nmaro/ooth/blob/c400796ee0a5cd83d106f6b6dabeb93103691829/packages/ooth-local/src/index.js#L6. I believe that the current accepted default for most bcrypt libraries is 12. I would recommend either raising that default to 12, or having it be a parameter that can be passed in by the user so they can choose their own values.
I've recently come across this article https://hackernoon.com/your-node-js-authentication-tutorial-is-wrong-f1a3bf831a46 which does a pretty good job at listing the usual problems with node js authentication tutorials, and it's a good read for things to keep in mind.

**Comment by nmaro** [comment]
Hey thank you for the hint. I raised it to 12. I'm actually aware of that article, introduced token hashing and other things because of it :) but I missed the cost factor thing. Patch incoming.
