### ISSUE TITLE
Facebook strategy is creating multiple accounts

### ISSUE THREAD

**Issue by Quexten** [nmaro/ooth#50]
### Steps to reproduce
When i'm signing, using the Facebook strategy, then log out, then sign in again, ooth creates a new account with a new userId, which, in the Facebook strategy contains the same id field as the first account. Noteworthy might be that i do not provide the email via Facebook oauth, since you can unselect it in the Facebook oauth consent screen.

### Expected behaviour
The same userId should be used to sign in.

### Temporary Fix
Replace
https://github.com/nmaro/ooth/blob/dce4a156e375e8ceaf7235730bda7997466986f1/packages/ooth-facebook/src/index.js#L16

with
`registerUniqueField('id', 'id');`

I didn't submit a pull request though, i'm not sure if this is the intended way to fix or if there is any specific reason why `registerStrategyUniqueField('id');` is used.

**Comment by nmaro** [comment]
Ok can confirm this happens.

**Comment by nmaro** [comment]
Should be fixed.
