### ISSUE TITLE
Ooth local: make password tests configurable

### ISSUE THREAD

**Issue by jonpacker** [nmaro/ooth#57]
Currently the password strictness tests are not exposed and aren't configurable, such that when using `ooth-local` I just have to accept that all user passwords must contain a number, a lowercase letter, an uppercase letter and be at least 6 characters long. I would prefer I could configure this myself.

**Comment by nmaro** [comment]
Sounds good.

**Comment by nmaro** [comment]
If you feel up to it feel free to make a pull request with an optional parameter `tests` for ooth local. Ooth local should then check if `tests` is defined and merge it with the `tests` const [here](https://github.com/nmaro/ooth/blob/master/packages/ooth-local/src/index.js#L10) (rename that one to TESTS).

**Comment by nmaro** [comment]
should be 3 lines of code (except the ones for the rename).

**Comment by nmaro** [comment]
Done
