### ISSUE TITLE
Ooth local: no way to programmatically create a user

### ISSUE THREAD

**Issue by jonpacker** [nmaro/ooth#58]
It seems like the logic for inserting an Ooth local user with hashed password is [inside an express route](https://github.com/nmaro/ooth/blob/master/packages/ooth-local/src/index.js#L201), and this is the only place it exists. Because of the prerequisite of `ooth-roles` that a user has to have their role set manually to admin, it seems like there's no good way to programmatically create that first user if they don't exist and give them an admin role. I could recreate the password hashing that is going on inside `ooth-local`, but this seems like a really bad idea. Is there something I'm missing here?

**Comment by nmaro** [comment]
That is a good point. Your observation is correct. Looks like this would solve the issue: https://github.com/nmaro/ooth/issues/49.

If you are in a hurry a workaround could be to create an user via http and then modify it via a command to mongodb. Both are ugly, I know :grin:

**Comment by gferreri** [comment]
In our scenario, we'd like to build an interface where an admin user can create other users, but we're running into a host of issues, primarily stemming from a lack of a programmatic interface. Also, calls to the local strategy's `register` endpoint can only be made by a user who is not already logged in, which kills the ability for us to use the `register` endpoint from the client-side at all.

**Comment by aaronmgdr** [comment]
I had this same issue. I ended up studying insides of ooth and creating something similar that is compatable. I have removed the application specific parts but here it is

```
const generator = require('generate-password');
const OothMongo = require('ooth-mongo');
const {ObjectId} = require('mongodb');
const { hashSync, genSaltSync } = require('bcrypt-nodejs');
const { randomBytes } = require('crypto');
const SALT_ROUNDS = 12;

const HOUR = 1000 * 60 * 60;


function randomToken() {
  return randomBytes(43).toString('hex');
}


function hash(pass) {
  return hashSync(pass, genSaltSync(SALT_ROUNDS));
}

class UserImporter {
  backend: {
    getUserByValue: Function,
    insertUser: Function
  }
  
  constructor(db) {
    this.backend = new OothMongo(db, ObjectId);
  }
   /// call this to create a user
  immmigrate({email, firstName, lastName, phone}) {
    if (typeof email !== 'string') {
      throw new Error(`Invalid email ${email}`);
    }
      
    return this.backend.getUserByValue(['local.email'], email).then(user => {
      if (user) {
        console.error(`This email ${email} is already registered.`);
        return
      }
      const password = generate.password()
      const verificationToken = randomToken();
    
      this.backend.insertUser({
        profile:  {
          firstName,
          lastName,
          phone
        },
        local: {
          email,
          password: hash(password),
          verificationToken: hash(verificationToken),
          verificationTokenExpiresAt: new Date(Date.now() + HOUR)
        },
        roles
      }).then(_id => {  console.info(`User ${email} imported successfully.`);
    });
  }
}

export default UserImporter

```

**Comment by aboe026** [comment]
what is the `roles` variable?

**Comment by nmaro** [comment]
@jonpacker thanks for the feedback, what approach did you end up taking?

**Comment by nmaro** [comment]
For the specific case of `ooth-local` it is now possible to run

`ooth.on('register', ({_id, email, verificationToken}) => ...))`

`await ooth.callMethod('local', 'register', { email, password })`

The general idea is that every method registered with `ooth.registerMethod` can now be called like that.

**Comment by fractefactos** [comment]
> For the specific case of `ooth-local` it is now possible to run
> 
> `ooth.on('register', ({_id, email, verificationToken}) => ...))`
> 
> `await ooth.callMethod('local', 'register', { email, password })`
> 
> The general idea is that every method registered with `ooth.registerMethod` can now be called like that.

What's the ooth.on event callback for "login", that exist?
