### ISSUE TITLE
Additional fields

### ISSUE THREAD

**Issue by jmarceli** [nmaro/ooth#60]
Hi, is it possible to provide additional fields inside API response?

Currently using **ooth-local** login or getStatus I get response similar to this:
```
{"user":{"_id":"5af48ba5b91e401fb62800c6","local":{"email":"test@test.com"}}}
```
Is it possible to add for example **permissions** key to get response similar to this:
```
{"user":{"_id":"5af48ba5b91e401fb62800c6","local":{"email":"test@test.com","permissions":"admin"}}}
```

**Comment by nmaro** [comment]
For this specific use case use the `ooth-roles` plugin. https://github.com/nmaro/ooth/wiki/Plugins#managing-user-roles

**Comment by jmarceli** [comment]
Thanks, it looks like something that I was looking for.
