### ISSUE TITLE
ooth-local-emailer url parameter

### ISSUE THREAD

**Issue by Sparki2002** [nmaro/ooth#65]
The url parameter doesn't do anything (it isn't even used in [code](https://github.com/nmaro/ooth/blob/master/packages/ooth-local-emailer/src/index.js))
```js
ooth.use("local", oothLocal(emailer({
  from: "XXX",
  siteName: "XXX",
  url: "XXX",
  sendMail: mail({
    apiKey: "XXX",
    domain: "XXX"
  })
})));
```

**Comment by nmaro** [comment]
Thanks. Removed.
