### ISSUE TITLE
prisma backend?

### ISSUE THREAD

**Issue by agustif** [nmaro/ooth#72]
Would love to make a prisma-backend integrator to be able to use ooth/staart for my own project.

I saw #47 about Postgres.

It should be pretty easy with the use of prisma-bindings forwardTo('db');

It also should be easy to integrate on backend development examples, as both use docker to build the backend.

It also could be integrable using the generated mongodb to start from, but it should be easy to integrate with an existing project, without regards of the db.

I think being flexible about this, and not tidying up ooth to mongo could be helpful to make it more useful to a broader audience.

I also think we could leverage GraphQL-Shield for role-based/permissions/authorization

**Comment by nmaro** [comment]
Sounds like a cool idea. Would you be willing to try implementing this?
As a starting point you could use the [standalone example](https://github.com/nmaro/ooth/tree/master/examples/standalone) (copy and paste it into a `prisma`) folder, and implement the new ooth backend inside the folder. I can then publish the backend as a package and you could then import it to complete the example, which I would merge. What do you think? For easier communication you could join the [slack channel](https://join.slack.com/t/ooth/shared_invite/enQtMjQ3MDE2ODA2NjE0LTE1NGNmN2YzZTdiMWNjODExZmNjYzg3ZGJjZmVmZmI2YjVhOWYzZDQ1NWI4Y2JiNzNlMmI2Y2U5ZWFhODIzMWQ).

**Comment by JovaanB** [comment]
Is it now possible to integrate prisma in Ooth ?
