### ISSUE TITLE
MongoDB Connection Error in Production (Unexpected token < in JSON)

### ISSUE THREAD

**Issue by aaronsmulktis** [nmaro/ooth#9]
After getting everything setup and working nicely locally, I get this error (in production) when trying to hit my root `/` page:
`FetchError: invalid json response body at http://app-staging.field-test.co/auth/status reason: Unexpected token < in JSON at position 0`

Even if I update from `localhost` to `<live domain>` or `<live domain>:4000` in the `MongoClient.connect()` function...

**Comment by aaronsmulktis** [comment]
I've also tried seeding mongo w a user, which didn't seem to help

**Comment by nmaro** [comment]
As we discussed privately this was not an ooth problem.
